<?php

namespace App\Emotion\Domain\Model\TertiaryEmotion;

enum TertiaryEmotionLabelEnum: string
{
    case HESITANT = 'hesitant';
    case AVERSION = 'aversion';
    case DETESTABLE = 'detestable';
    case REVULSION = 'revulsion';
    case REVOLTED = 'revolted';
    case REPUGNANT = 'repugnant';
    case LOATHING = 'loathing';
    case JUDGMENTAL = 'judgmental';
    case SARCASTIC = 'sarcastic';
    case SKEPTICAL = 'skeptical';
    case SUSPICIOUS = 'suspicious';
    case WITHDRAWN = 'withdrawn';
    case IRRITATED = 'irritated';
    case INFURIATE = 'infuriate';
    case HOSTILE = 'hostile';
    case PROVOKED = 'provoked';
    case ENRAGED = 'enraged';
    case FURIOUS = 'furious';
    case VIOLATED = 'violated';
    case RESENTFUL = 'resentful';
    case JEALOUS = 'jealous';
    case INSECURE = 'insecure';
    case DEVASTATED = 'devastated';
    case EMBARRASSED = 'embarrassed';
    case RIDICULED = 'ridiculed';
    case DISRESPECTED = 'disrespected';
    case ALIENATED = 'alienated';
    case INADEQUATE = 'inadequate';
    case INSIGNIFICANT = 'insignificant';
    case WORTHLESS = 'worthless';
    case INFERIOR = 'inferior';
    case WORRIED = 'worried';
    case OVERWHELMED = 'overwhelmed';
    case FRIGHTENED = 'frightened';
    case TERRIFIED = 'terrified';
    case SHOCKED = 'shocked';
    case DISMAYED = 'dismayed';
    case DISILLUSIONED = 'disillusioned';
    case PERPLEXED = 'perplexed';
    case ASTONISHED = 'astonished';
    case AWE = 'awe';
    case EAGER = 'eager';
    case ENERGETIC = 'energetic';
    case LIBERATED = 'liberated';
    case ECSTATIC = 'ecstatic';
    case AMUSED = 'amused';
    case INQUISITIVE = 'inquisitive';
    case IMPORTANT = 'important';
    case CONFIDENT = 'confident';
    case RESPECTED = 'respected';
    case FULFILLED = 'fulfilled';
    case COURAGEOUS = 'courageous';
    case PROVOCATIVE = 'provocative';
    case LOVING = 'loving';
    case HOPEFUL = 'hopeful';
    case SENSITIVE = 'sensitive';
    case PLAYFUL = 'playful';
    case OPEN = 'open';
    case INSPIRED = 'inspired';
    case INDIFFERENT = 'indifferent';
    case APATHETIC = 'apathetic';
    case ISOLATED = 'isolated';
    case ABANDONED = 'abandoned';
    case EMPTY = 'empty';
    case VULNERABLE = 'vulnerable';
    case POWERLESS = 'powerless';
    case VICTIMIZED = 'victimized';
    case IGNORED = 'ignored';
    case ASHAMED = 'ashamed';
    case REMORSEFUL = 'remorseful';
}